### ISSUE TITLE
Kruskal's Algorithm using stl in C++

### ISSUE THREAD

**Issue by akshkr** [ai-coder/Algorithms_using_stl#20]
use comment lines to describe your code

**Comment by vomitaftertaste** [comment]
I like to take this if nobody else is working on it

**Comment by akshkr** [comment]
definitely

**Comment by j07nikita** [comment]
I wanna work on it. PLEASE....

**Comment by j07nikita** [comment]
I have added the code for Kruskal's algo, please review it.

**Comment by vomitaftertaste** [comment]
@j07nikita go ahead man :)

**Comment by akshkr** [comment]
Done. You can also add codes of your own which are not listed in the issue.
